/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Accounts"
 *
 * @author Telosys
 *
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name="accounts", schema="dbo", catalog="HDWatch" )
public class Accounts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="username", nullable=false, length=50)
    private String     username ;

    //--- ENTITY DATA FIELDS 
    @Column(name="activated", nullable=false)
    private Boolean    activated ;

    @Column(name="email", nullable=false, length=50)
    private String     email ;

    @Column(name="fullname", nullable=false, length=50)
    private String     fullname ;

    @Column(name="password", nullable=false)
    private String     password ;

    @Column(name="google", length=2147483647)
    private String     google ;

    @Column(name="facebook", length=2147483647)
    private String     facebook ;
    

    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="accounts")
    private List<Favorites> listOfFavorites ; 
    
    @JsonIgnore
    @OneToMany(mappedBy="accounts")
    private List<Orders> listOfOrders ; 
    
    @JsonIgnore
    @OneToMany(mappedBy="accounts", fetch = FetchType.EAGER)
    private List<Roledetails> listOfRoledetails ; 

    @JsonIgnore
    @OneToMany(mappedBy="accounts")
    private List<Carts> listOfCarts ; 

}
