/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;
import javax.transaction.Transactional;

import org.springframework.data.mapping.AccessOptions.SetOptions.Propagation;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Accounts"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="accounts", schema="dbo", catalog="HDWatch" )
public class Accounts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=50)
    private String     username ;

    @Column(name="activated", nullable=false)
    private Boolean    activated ;

    @Column(name="email", nullable=false, length=50)
    private String     email ;

    @Column(name="fullname", nullable=false, length=50)
    private String     fullname ;

    @Column(name="password", nullable=false, length=50)
    private String     password ;

    @Column(name="google", length=2147483647)
    private String     google ;

    @Column(name="facebook", length=2147483647)
    private String     facebook ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="accounts")
    private List<Favorites> listOfFavorites ; 
    
    @JsonIgnore
    @OneToMany(mappedBy="accounts")
    private List<Orders> listOfOrders ; 
    
    @JsonIgnore
    @OneToMany(mappedBy="accounts",fetch = FetchType.EAGER)
    private List<Roledetails> listOfRoledetails ; 

    @JsonIgnore
    @OneToMany(mappedBy="accounts")
    private List<Carts> listOfCarts ; 


    /**
     * Constructor
     */
    public Accounts() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setActivated( Boolean activated ) {
        this.activated = activated ;
    }
    public Boolean getActivated() {
        return this.activated;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setFullname( String fullname ) {
        this.fullname = fullname ;
    }
    public String getFullname() {
        return this.fullname;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    public void setGoogle( String google ) {
        this.google = google ;
    }
    public String getGoogle() {
        return this.google;
    }

    public void setFacebook( String facebook ) {
        this.facebook = facebook ;
    }
    public String getFacebook() {
        return this.facebook;
    }

    //--- GETTERS FOR LINKS
    public List<Favorites> getListOfFavorites() {
        return this.listOfFavorites;
    } 

    public List<Orders> getListOfOrders() {
        return this.listOfOrders;
    } 

    public List<Roledetails> getListOfRoledetails() {
        return this.listOfRoledetails;
    } 

    public List<Carts> getListOfCarts() {
        return this.listOfCarts;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(activated);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(fullname);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(google);
        sb.append("|");
        sb.append(facebook);
        return sb.toString(); 
    } 

}
