/*
 * Created on 2023-06-10 ( 09:58:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "Brands"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="brands", schema="dbo", catalog="HDWatch" )
public class Brands implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Column(name="images", nullable=false, length=50)
    private String     images ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="brands")
    private List<Products> listOfProducts ; 

}
