/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Cartdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="cartdetails", schema="dbo", catalog="HDWatch" )
public class Cartdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="cart_id", nullable=false)
    private Integer    cartId ;

    @Column(name="product_id", nullable=false)
    private Integer    productId ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;

    @Column(name="price", nullable=false)
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="cart_id", referencedColumnName="id", insertable=false, updatable=false)
    private Carts      carts ; 

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 


    /**
     * Constructor
     */
    public Cartdetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setCartId( Integer cartId ) {
        this.cartId = cartId ;
    }
    public Integer getCartId() {
        return this.cartId;
    }

    public void setProductId( Integer productId ) {
        this.productId = productId ;
    }
    public Integer getProductId() {
        return this.productId;
    }

    public void setQuantity( Integer quantity ) {
        this.quantity = quantity ;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    //--- GETTERS FOR LINKS
    public Carts getCarts() {
        return this.carts;
    } 

    public Products getProducts() {
        return this.products;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(cartId);
        sb.append("|");
        sb.append(productId);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 

}
