/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Favoritedetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="favoritedetails", schema="dbo", catalog="HDWatch" )
public class Favoritedetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="favorite_id", nullable=false)
    private Integer    favoriteId ;

    @Column(name="product_id", nullable=false)
    private Integer    productId ;

    @Column(name="available")
    private Boolean    available ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 

    @ManyToOne
    @JoinColumn(name="favorite_id", referencedColumnName="id", insertable=false, updatable=false)
    private Favorites  favorites ; 


    /**
     * Constructor
     */
    public Favoritedetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setFavoriteId( Integer favoriteId ) {
        this.favoriteId = favoriteId ;
    }
    public Integer getFavoriteId() {
        return this.favoriteId;
    }

    public void setProductId( Integer productId ) {
        this.productId = productId ;
    }
    public Integer getProductId() {
        return this.productId;
    }

    public void setAvailable( Boolean available ) {
        this.available = available ;
    }
    public Boolean getAvailable() {
        return this.available;
    }

    //--- GETTERS FOR LINKS
    public Products getProducts() {
        return this.products;
    } 

    public Favorites getFavorites() {
        return this.favorites;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(favoriteId);
        sb.append("|");
        sb.append(productId);
        sb.append("|");
        sb.append(available);
        return sb.toString(); 
    } 

}
