/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Favoritedetails"
 *
 * @author Telosys
 *
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name="favoritedetails", schema="dbo", catalog="HDWatch" )
public class Favoritedetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="favorite_id", nullable=false)
    private Integer    favoriteId ;

    @Column(name="product_id", nullable=false)
    private Integer    productId ;

    @Column(name="available")
    private Boolean    available ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 

    @ManyToOne
    @JoinColumn(name="favorite_id", referencedColumnName="id", insertable=false, updatable=false)
    private Favorites  favorites ; 

}
