/*
 * Created on 2023-06-10 ( 09:58:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "Favoritedetails"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="favoritedetails", schema="dbo", catalog="HDWatch" )
public class Favoritedetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="favoriteId", nullable=false)
    private Integer    favoriteid ;

    @Column(name="productId", nullable=false)
    private Integer    productid ;

    @Column(name="available")
    private Boolean    available ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="productId", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 

    @ManyToOne
    @JoinColumn(name="favoriteId", referencedColumnName="id", insertable=false, updatable=false)
    private Favorites  favorites ; 

}
