/*
 * Created on 2023-06-10 ( 09:58:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="orderdetails", schema="dbo", catalog="HDWatch" )
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="orderId", nullable=false)
    private Integer    orderid ;

    @Column(name="productId", nullable=false)
    private Integer    productid ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="orderId", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders ; 

    @ManyToOne
    @JoinColumn(name="productId", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 

}
