/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name="orderdetails", schema="dbo", catalog="HDWatch" )
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="order_id", nullable=false)
    private Integer    orderId ;

    @Column(name="product_id", nullable=false)
    private Integer    productId ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders ; 

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 

}
