/*
 * Created on 2023-06-10 ( 09:58:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "Orders"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="orders", schema="dbo", catalog="HDWatch" )
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="accountId", nullable=false)
    private Integer    accountid ;

    @Column(name="address", nullable=false, length=50)
    private String     address ;

    @Temporal(TemporalType.DATE)
    @Column(name="craeteDate", nullable=false)
    private Date       craetedate ;

    @Column(name="status", nullable=false, length=50)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="orders")
    private List<Orderdetails> listOfOrderdetails ; 

    @ManyToOne
    @JoinColumn(name="accountId", referencedColumnName="id", insertable=false, updatable=false)
    private Accounts   accounts ; 

}
