/*
 * Created on 2023-06-16 ( 14:09:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Orders"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="orders", schema="dbo", catalog="HDWatch" )
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="account_id", nullable=false)
    private Integer    accountId ;

    @Column(name="address", nullable=false, length=50)
    private String     address ;

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", nullable=false)
    private Date       createDate ;

    @Column(name="status", nullable=false, length=50)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="orders")
    private List<Orderdetails> listOfOrderdetails ; 

    @ManyToOne
    @JoinColumn(name="account_id", referencedColumnName="id", insertable=false, updatable=false)
    private Accounts   accounts ; 


    /**
     * Constructor
     */
    public Orders() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setAccountId( Integer accountId ) {
        this.accountId = accountId ;
    }
    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate ;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    //--- GETTERS FOR LINKS
    public List<Orderdetails> getListOfOrderdetails() {
        return this.listOfOrderdetails;
    } 

    public Accounts getAccounts() {
        return this.accounts;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(accountId);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
