/*
 * Created on 2023-06-15 ( 14:26:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Productimagedetail"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="productimagedetail", schema="dbo", catalog="HDWatch" )
public class Productimagedetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product_id", nullable=false)
    private Integer    productId ;

    @Column(name="product_img_id", nullable=false)
    private Integer    productImgId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="product_img_id", referencedColumnName="id", insertable=false, updatable=false)
    private Productimages productimages ; 

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products ; 


    /**
     * Constructor
     */
    public Productimagedetail() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setProductId( Integer productId ) {
        this.productId = productId ;
    }
    public Integer getProductId() {
        return this.productId;
    }

    public void setProductImgId( Integer productImgId ) {
        this.productImgId = productImgId ;
    }
    public Integer getProductImgId() {
        return this.productImgId;
    }

    //--- GETTERS FOR LINKS
    public Productimages getProductimages() {
        return this.productimages;
    } 

    public Products getProducts() {
        return this.products;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(productId);
        sb.append("|");
        sb.append(productImgId);
        return sb.toString(); 
    } 

}
