/*
 * Created on 2023-06-10 ( 09:58:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "Roles"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="roles", schema="dbo", catalog="HDWatch" )
public class Roles implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="role", nullable=false, length=50)
    private String     role ;

    @Column(name="description", nullable=false, length=50)
    private String     description ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="roles")
    private List<Roledetails> listOfRoledetails ; 

}
