/*
 * Created on 2023-06-10 ( 09:58:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "Roledetails"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="roledetails", schema="dbo", catalog="HDWatch" )
public class Roledetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="accountId", nullable=false)
    private Integer    accountid ;

    @Column(name="roleId", nullable=false)
    private Integer    roleid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="accountId", referencedColumnName="id", insertable=false, updatable=false)
    private Accounts   accounts ; 

    @ManyToOne
    @JoinColumn(name="roleId", referencedColumnName="id", insertable=false, updatable=false)
    private Roles      roles ; 

}
