/*
 * Created on 2023-06-15 ( 14:26:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Roles"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="roles", schema="dbo", catalog="HDWatch" )
public class Roles implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="role", nullable=false, length=50)
    private String     role ;

    @Column(name="description", nullable=false, length=50)
    private String     description ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="roles")
    private List<Roledetails> listOfRoledetails ; 


    /**
     * Constructor
     */
    public Roles() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setRole( String role ) {
        this.role = role ;
    }
    public String getRole() {
        return this.role;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    //--- GETTERS FOR LINKS
    public List<Roledetails> getListOfRoledetails() {
        return this.listOfRoledetails;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(role);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}
