/*
 * Created on 2023-06-10 ( 09:58:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import lombok.Data;

/**
 * JPA entity class for "SaleEvents"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sale_events", schema="dbo", catalog="HDWatch" )
public class SaleEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=255)
    private String     name ;

    @Temporal(TemporalType.DATE)
    @Column(name="startDate", nullable=false)
    private Date       startdate ;

    @Temporal(TemporalType.DATE)
    @Column(name="endDate", nullable=false)
    private Date       enddate ;

    @Column(name="priceSale", nullable=false)
    private Integer    pricesale ;


    //--- ENTITY LINKS ( RELATIONSHIP )

}
