/*
 * Created on 2023-06-15 ( 14:26:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hdwatch.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "SaleEvents"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="sale_events", schema="dbo", catalog="HDWatch" )
public class SaleEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=255)
    private String     name ;

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false)
    private Date       startDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false)
    private Date       endDate ;

    @Column(name="priceSale", nullable=false)
    private Integer    pricesale ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public SaleEvents() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setStartDate( Date startDate ) {
        this.startDate = startDate ;
    }
    public Date getStartDate() {
        return this.startDate;
    }

    public void setEndDate( Date endDate ) {
        this.endDate = endDate ;
    }
    public Date getEndDate() {
        return this.endDate;
    }

    public void setPricesale( Integer pricesale ) {
        this.pricesale = pricesale ;
    }
    public Integer getPricesale() {
        return this.pricesale;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(startDate);
        sb.append("|");
        sb.append(endDate);
        sb.append("|");
        sb.append(pricesale);
        return sb.toString(); 
    } 

}
